src/app.tsx, src/chain-data/helpers.ts, src/components/sign-in/sign-in.tsx, src/pages/history/history.tsx, src/pages/proposal-commons/proposal-list/proposal-list.tsx, src/pages/proposals/proposals.tsx
* Rename active proposal path from `proposal` to `governance`, because otherwise the navigation button won't be highlighted. This also matches the convention for history page.
* Rename proposals to `active proposals` or `past proposals`
* Minor changes to unsupported network modal
=> Minor fixes

src/components/input/input.tsx, src/pages/proposals/proposals.tsx
1. Number inputs now completely prevent negative numbers from being entered by default. Number inputs are only used on the dashboard modals and as the "ETH value" when creating a new proposal, so this shouldn't cause any issues
2. Only display the "The genesis epoch is over." tooltip item during the genesis epoch, after which it will always be hidden (but still validated)
https://github.com/api3dao/api3-dao-dashboard/issues/184
=> Prevent negative numbers and hide genesis epoch checklist item

src/components/notifications/notifications.tsx
My motivation for sending even the handled errors was to have better understanding what issues will our users have.
This turned out pretty well, but now the issues keep repeating and they are polluting the sentry dashboard (and we can do nothing about them since they are handled already).
In this PR, I'm changing this to only don't send these errors by default.
=> Do not send handled errors to sentry anymore

hardhat/scripts/next-epoch.ts
I was having an issue when testing creating proposals where the "genesis epoch is over" check was still disabling the button, even after running the `next-epoch.ts` script. I did a bit of digging and it seems like simply increasing the time is not enough. We also need to mine a new block as the [isGenesisEpoch() function](https://github.com/api3dao/api3-dao/blob/c745454d60ad97f6ffa9b5aa612c9a2b7eba16d0/packages/pool/contracts/StateUtils.sol#L418-L425) looks at the current block's timestamp.
The issue can be replicated by doing the following steps in order:
1. Starting a fresh Ethereum node
2. Deploying the DAO contracts
3. Sending ETH and enough API3 to your wallet.
4. Staking the API3
5. Running the `next-epoch` script
6. Navigating to the governance page
This can also be done by sending …
=> Force a new block after increasing the time

.npmrc
I was getting an error when trying to run the new setup scripts locally. I'm guessing this is related to how I have Node.js setup locally. Found a fix here: https://stackoverflow.com/a/51295237 that resolved it for me.
1. Add a `.npmrc` file with `scripts-prepend-node-path=true`
=> Add .npmrc to fix intermittent script bug

.dockerignore, Dockerfile, README.md
IPFS-hosted connectivity raises many complaints on dashboard functionality
The decentralized way of running dashboard from a local machine can be spread to address these issues.
=> running dashboard for mainnet in docker

.gitignore, README.md, package.json, yarn.lock
I noticed that making any frontend code changes causes a runtime error in the HMR mechanism:
https://github.com/facebook/create-react-app/issues/11773
Turned out to be an issue with react-scripts v4 (in combo with its react-error-overlay dependency). Long term fix would be to upgrade to react-scripts v5, but for now pinning react-error-overlay to v6.0.9 fixes the problem.
=> Fix HMR by pinning react-error-overlay to v6.0.9 (via a resolution)

.github/workflows/main.yml
Currently updating the keys is the only way to do it: 
https://github.community/t/how-to-clear-cache-in-github-actions/129038
https://stackoverflow.com/questions/63521430/clear-cache-in-github-actions
=> DAO-152 Update Github actions cache keys (to force it to create new caches)

dev-scripts/claims-manager/deploy-on-hardhat.js, hardhat/hardhat.config.ts
At this stage it's still quite a process to test locally, but the current steps are:
1. Clone https://github.com/api3dao/claims-manager
2. cd into claims-manager repo and run:
`yarn && yarn build`
3. (still in the claims-manger repo) :
`npx hardhat run ../api3-dao-dashboard/dev-scripts/claims-manager/deploy-on-hardhat.js  --network localhost`
4. In api3-doa-dashboard repo, set REACT_APP_CLAIMS_MANAGER_ADDRESS in .env (address gets printed out in previous step)
4. cd into the api3-dao-dashboard/hardhat folder and create yourself a policy:
`npx hardhat create-user-policy --address YOUR_ADDRESS --coverage-amount 500 --ipfs-hash some-hash-001`
5. Start your dev server and use the policy hash printed out in previous step to navigate to:
http://localhost:3000/#/policies/POLICY_HASH
From there …
=> Add ClaimsManager deploy and seed scripts

README.md
Also updates the running from docker instructions to run DAO dashboard from "production" branch instead of "main".
=> Clarify main and production branch relationship

src/components/button/button.module.scss, src/components/button/button.tsx, src/components/layout/error-reporting-notice/error-reporting-notice.tsx, src/components/layout/layout.module.scss, src/components/layout/layout.tsx, src/components/sign-in/sign-in.module.scss, src/components/sign-in/sign-in.tsx, src/pages/claim-details/claim-actions.tsx, src/pages/claims/claims.tsx, src/pages/dashboard/dashboard.tsx, src/pages/dashboard/forms/confirm-unstake-form.tsx, src/pages/dashboard/forms/forms.module.scss, src/pages/dashboard/forms/token-amount-form.tsx, src/pages/dashboard/forms/token-deposit-form.tsx, src/pages/dashboard/pending-unstake-panel/pending-unstake-panel.tsx, src/pages/dashboard/unstake-banner/unstake-banner.tsx, src/pages/policies/policies.tsx, src/pages/policies/policy-list.tsx, src/pages/proposal-commons/proposal-details/proposal-details.module.scss, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposal-commons/proposal-details/vote-form/vote-form.tsx, src/pages/proposal-commons/proposal-list/proposal-list.tsx, src/pages/proposal-commons/proposal-list/proposal-status/proposal-status.module.scss, src/pages/proposal-commons/proposal-list/proposal-status/proposal-status.tsx, src/pages/proposals/delegation/delegation.module.scss, src/pages/proposals/delegation/delegation.tsx, src/pages/proposals/forms/choose-delegate-action/choose-delegate-action.tsx, src/pages/proposals/forms/delegate/delegate-form.tsx, src/pages/proposals/forms/new-proposal-form.tsx
- Uses a pure CSS solution for the Button underline
- Removes the wrapping div
- Renames the `type` prop to `variant` (type clashes with the HTML button type prop)
- Updates props to accept any HTML button prop
I used an absolutely positioned pseudo `::after` element to create the underline. In order to have no visual impact, a `margin-bottom` was added as well to the button to cater for the underline's space.
I went through all the Button usages where a `className` was used, and adjusted the CSS to no longer target a nested `button` element.
=> DAO-166 Button component improvements

.github/workflows/main.yml, src/components/timer/timer.tsx
It fixes the missing binary issue: https://docs.cypress.io/guides/continuous-integration/introduction#Missing-binary
The issue occurred on a couple of builds today: https://github.com/api3dao/api3-dao-dashboard/runs/7354402845?check_suite_focus=true
The cypress binary gets installed via a `postinstall` hook that sometimes doesn't trigger, so the additional `yarn cypress install` command installs the binary only if it is not present (otherwise it skips)
=> DAO-173 Add additional cypress install to "Install Dependencies" step

.eslintrc.json, src/contracts/hooks.ts, src/logic/claims/data.ts, src/logic/policies/data.ts
The existing `usePossibleChainDataUpdate()` hook accepts a callback that it triggers:
- on mount
- when account or network changes
- when a new block is mined
In my usage of this hook, my callback loads a policy by its id (which we get from the URL):
```ts
const callback = useCallback(async () => {
// Load policy...
, [policyId]);
usePossibleChainDataUpdate(callback);
```
**The main issue:**
When you update the policy id in the URL, the callback doesn't get triggered again, and the UI gets out of sync.
**Additional issue:**
When multiple async calls are pending at the same time, there is no way to ensure that you only use the result from the latest call (as the async calls could resolve out of order).
Traditionally, these issues can be solved with `useEffect()`.
E.g. Basic example of …
=> DAO-183 Fix policy and claim details loading (with new useChainUpdateEffect() hook)

src/components/external-link/external-link.test.tsx, src/components/external-link/external-link.tsx
Updates the ExternalLink component to only accept URLs that start with "https://" or "http://"
=> DAO-196 Sanitise URL in ExternalLink component

cypress/integration/malicious-proposal-validation.spec.ts, cypress/integration/new-proposal.spec.ts, src/logic/proposals/encoding/encoding.test.ts, src/logic/proposals/encoding/encoding.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposals/forms/new-proposal-form.tsx
It fixes a false positive. The "This proposal is potentially malicious" warning incorrectly shows when the proposal has a non-zero ETH value. We currently don't have any proposals on mainnet with a non-zero ETH value, so no false positives are currently showing on mainnet.
Instead of providing the wei value to the `goEncodeEvmScript()` when re-encoding, the value gets formatted:
```diff
-  targetValue: decodedEvmScript.value.toString(),
+  targetValue: utils.formatEther(decodedEvmScript.value),
```
=> DAO-194 Fix false positive w.r.t. EVM script mismatch

package.json, yarn.lock
- sorts out nested dependencies
- ansi-regex
- async
- json-schema
- path-parse
- removes `npx` as it is bundled with `npm`, which in turn is bundled with node
- replaces the deprecated `node-sass` with `sass`
These changes reduce the size of `node_modules` from 1GB down to 720MB
~~I deleted and regenerated the `yarn.lock` file.~~
=> DAO-197 Dependency housekeeping 

src/chain-data/state.ts, src/logic/claims/data.ts, src/pages/claim-details/claim-actions.test.tsx, src/pages/claim-details/claim-actions.tsx
It shows when a ruling has been appealed and distinguishes whether it was the claimant or API3 who appealed.
The dispute object got a new `appealedBy` property which we use to determine if the ruling has been appealed (when the dispute `status` is `Waiting`)
```ts
dispute: null | {
id: string;
status: DisputeStatus;
ruling: ArbitratorRuling;
appealedBy: null | string;
};
```
=> DAO-192 Indicate when a ruling has been appealed

Dockerfile, README.md
Fixes https://linear.app/api3-dao/issue/DAO-205/verify-dao-dashboard-in-docker-works-on-all-platforms
Initially it was reported that the dockerized version is not working on Windows, but I realized it doesn't work also on the new m1 macOS (due to a different issue). 
* The windows issue is caused by broken symlinks when cloning the repo locally. This also means it's not possible to develop using Windows for which I've added a note. The fix is to clone the repo inside docker (again).
* MacOS issue is caused by missing libraries and we had the [same issue in Airnode](https://github.com/api3dao/airnode/blob/master/docker/Dockerfile#L5) so I just copied over the solution.
I've also changed the instructions in the README to clone the repo using HTTPS instead of SSH since the SSH requires more …
=> Fix Dockerization issues

dev-scripts/copy-localhost-data.js
It prevents overwriting an existing `localhost-dao.json` file in the postinstall script, so that you don't lose your deployed addresses unnecessarily.
If there is an existing `localhost-dao.json` file, we only continue overwriting it if its keys (i.e. contract names) don't match the example file's keys.
=> DAO-207 Prevent overwriting an existing localhost-dao.json file in postinstall script

src/chain-data/state.ts, src/logic/claims/data.ts, src/pages/claim-details/claim-actions.test.tsx, src/pages/claim-details/claim-actions.tsx, src/pages/claim-details/claim-details.module.scss, src/pages/claim-details/claim-details.tsx, src/pages/claim-details/payout-amount.tsx
- adds 
- proposed settlement amount
- remaining service coverage amount
- link to Policy Details page
- link to Kleros dispute resolver
- renames counterOfferAmountInUsd -> settlementAmountInUsd (copy changes will follow in [DAO-217](https://linear.app/api3-dao/issue/DAO-217))
=> DAO-200 Extend the summary section on the Claim Details page

hardhat/hardhat.config.ts, package.json, src/chain-data/state.ts, src/pages/claim-details/claim-actions.test.tsx, src/pages/claim-details/claim-actions.tsx, src/pages/claim-details/claim-details.tsx, src/pages/claim-details/payout-amount.tsx, src/utils/messages.ts
The bot should take care of executing the ruling for the user, so this Execute Payout action is needed for the when the bot fails to do its job (a corner case).
- adds a Execute Payout action when the arbitrator gave a `PayClaim` or a `PaySettlement` ruling, and the dispute is in the `Execution` period
- adds a `pass-dispute-period` Hardhat task in order to progress the dispute from the `Appeal` period to the `Execution` period
**Usage e.g.**
```
yarn claims:arbitrator-decide-to-pay-settlement --dispute-id 1 --appeal-period-length 0
yarn claims:pass-dispute-period --dispute-id 1
```
=> DAO-206 Add Execute Payout action for when the bot fails to execute the ruling for the user

src/components/back-button/back-button.module.scss, src/pages/claim-details/claim-details.module.scss, src/pages/claim-details/claim-details.tsx, src/pages/components/proposal-details/proposal-details.module.scss, src/pages/components/proposal-details/proposal-details.tsx, src/pages/policy-details/policy-details.module.scss, src/pages/policy-details/policy-details.tsx
- adds Policy ID, Active/Inactive, and Claims Allowed Until to Policy Details header
- adds Claim ID to Claim Details header
**Policy Details**
**Claim Details**
=> DAO-221 Policy and Claim Details header updates

src/pages/claim-details/claim-actions.module.scss, src/pages/claim-details/claim-actions.test.tsx, src/pages/claim-details/claim-actions.tsx, src/pages/claim-details/claim-details.module.scss, src/pages/claim-details/claim-details.tsx, src/pages/claim-details/payout-amount.module.scss, src/pages/claim-details/payout-amount.tsx, src/utils/messages.ts
- it aligns all the claim states on the Claim Details page with the latest designs (mostly wording changes)
- shows the payout USD amount (potentially clipped) at the top instead of the claim/settlement amount
- shows a notification/warning on the page when the payout amount exceeded the remaining coverage (a similar message was removed from the payout amount tooltip)
- shows a "Timed Out" status when we are past the deadline to escalate/accept a proposed settlement
- indicates when we are in the appeal period
- minor styling tweaks to align with the initial designs from Entrecasa/Leandro (expect some more tweaks to come)
(Not an exhaustive list)
=> DAO-217 Update claim states on Claim Details page

src/pages/claim-details/claim-actions.module.scss, src/pages/claim-details/claim-actions.tsx, src/pages/claim-details/confirmations.module.scss, src/pages/claim-details/confirmations.tsx
Adds a confirmation modal that informs/reminds the user that they will be paid out in API3 tokens when they accept the settlement or execute the payout.
=> DAO-190 Confirmation modals for accepting settlement and executing payout

Dockerfile
Same as #353 but for the `main` branch.
=> Pin main branch Docker parent image to node:16-alpine

src/components/usd-input/usd-input.tsx, src/pages/claim-details/claim-details.tsx, src/pages/components/policies/policy-list.tsx, src/pages/new-claim/new-claim-form.tsx, src/pages/policy-details/policy-details.tsx, src/utils/api3-format.test.ts, src/utils/api3-format.ts
- removes the $ symbol prefix and uses a USD suffix when formatting USD amounts
- rounds the USD amount when formatting (to 2 decimals)
=> DAO-218 Use USD suffix when formatting USD amounts

src/pages/claim-details/claim-actions.module.scss, src/pages/claim-details/claim-details.module.scss, src/pages/new-claim/new-claim.tsx, src/pages/policy-select/policy-select.tsx, src/utils/hooks.ts
- adds a scroll to top effect when moving between the New Claim steps
- adds a scroll to top effect for the Policy Select page
- uses the `useLayoutEffect()` hook to trigger the scroll (to avoid occasional flicker of "unscrolled" content)
=> DAO-224 Improve page transition scrolling for mobile

.github/workflows/build-docker.yml
Closes DAO-228 and DAO-161 (the latter once the secrets `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` are saved in the repo Settings).
This workflow builds the Docker image on a push to either `main` or `production`, whereas login & push to Docker Hub occurs only on the `production` branch. The production image is tagged with both `latest` and the SHA in the form of `sha-#######`. 
I've tested this on my fork:
- `main` [Action log](https://github.com/dcroote/api3-dao-dashboard/actions/runs/3457977495/jobs/5771934237): build but no push as expected
- `production` [Action log](https://github.com/dcroote/api3-dao-dashboard/actions/runs/3458031639/jobs/5772041116): login and push to repo - you can see the [tagged images here](https://hub.docker.com/r/dcroote/api3-dao-dashboard/tags). I've tested …
=> Add docker build and push CI workflow

cypress/e2e/claim-process-with-arbitration.cy.ts, cypress/e2e/claim-process.cy.ts, cypress/support/claims.ts, package.json, src/logic/claims/data.ts, src/pages/claim-details/claim-actions.tsx, src/pages/claim-details/confirmations.tsx, yarn.lock
- it adds the following Cypress tests:
- bumps `@testing-library/cypress` to get rid of some deprecation warnings
=> DAO-231 Cypress tests: Claim process with arbitration

src/chain-data/state.ts, src/components/icons/info-icon.tsx, src/components/timer/hooks.ts, src/components/timer/timer.tsx, src/logic/claims/data.test.ts, src/logic/claims/data.ts, src/pages/claim-details/claim-actions.test.tsx, src/pages/my-claims/claim-list.module.scss, src/pages/my-claims/claim-list.test.tsx, src/pages/my-claims/claim-list.tsx, src/pages/my-claims/evaluating-indicators.module.scss, src/pages/my-claims/evaluating-indicators.tsx, src/pages/my-claims/variables.scss
- it calculates a deadline for Kleros evaluation
- it uses a different mechanism for showing the remaining evaluation time (on the claim list) to better communicate that the deadline is on API3/Kleros' side
- it removes the "created at" date from the claim list items
Kleros gives their ruling after the `Vote` period, so when we are in the `Evidence` period, we get the vote period end date by adding the vote period to the evidence period (the commit period is skipped because the sub court does not have hidden votes).
```ts
// Evidence period
deadline = addSeconds(dispute.periodChangedAt, evidencePeriodLength + votePeriodLength);
```
The period lengths are provided by the sub court (`subCourt.timesPerPeriod[]`)
=> DAO-226 Claim list: Alternative mechanism for showing the evaluation time for API3/Kleros

.github/workflows/build-docker.yml, README.md
Updates the Action as in #365 and also updates the README to describe how to use the prebuilt Docker image.
=> Add prebuilt Docker instructions to README

config-overrides.js, package.json, yarn.lock
- upgrades react-scripts from v4 to v5
- introduces react-app-rewired in order to extend the Webpack configuration
We needed to extend the default Webpack config in order to:
- provide polyfills for some core node modules (react-scripts v5 uses Webpack v5, which no longer automatically polyfills core node modules, which some of our dependencies need)
- ignore source map warnings from our dependencies
- bundle the JS similar to v4
=> Upgrade react-scripts to v5 and introduce react-app-rewired

.gitignore, cypress/e2e/new-proposal.cy.ts, src/chain-data/state.ts, src/logic/proposals/encoding/encoding.test.ts, src/logic/proposals/encoding/encoding.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposal-commons/treasury/treasury.tsx, src/pages/proposals/forms/new-proposal-form.tsx
See: https://api3workspace.slack.com/archives/C02ALA11APM/p1683621470320789
Review commit by commit.
Initially, we used only a very loose validation of the proposal form. Later we improved this, but we also prevented a use case of simple ETH transfer. 
To support this use case, I've added special cases to the validation. If both target contract signature and parameters are empty, the validation passes and a proposal can be created. Since signature and parameters can be empty now, I think it makes sense to hide them in proposal details.
I've tested it manually locally, but creating e2e is complex so I opted for encoding unit tests only.
1. I filled the proposal form
2. After creating it, it got immediately executed (since I have all the voting power)
3. Proposal details
=> Allow simple ETH transfer proposals

src/logic/proposals/encoding/encoding.test.ts
#401 
It adds the tests back that was removed as part of the web3modal upgrade here: https://github.com/api3dao/api3-dao-dashboard/commit/d203177610586429f9b7fb3978156d295230eb6f#diff-d007a916315fd637a98142838e0bff7a8336ac91e5d2210aa5e50cb0d0915408L248
I have realised that we don't need to remove them completely, but that they should be adjusted.
=> Add tests around encoding ENS names back in

src/contracts/hooks.ts, src/pages/dashboard/dashboard.tsx, src/pages/dashboard/forms/token-deposit-form.tsx, src/pages/dashboard/pending-unstake-panel/pending-unstake-panel.tsx, src/pages/dashboard/unstake-banner/unstake-banner.tsx, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposal-commons/proposal-list/proposal-status/proposal-status.tsx, src/pages/proposals/delegation/delegation.tsx, src/pages/proposals/forms/delegate/delegate-form.tsx, src/pages/proposals/proposals.tsx, src/pages/vesting/vesting.tsx, src/wallet-connect.ts
It bumps the Wallet Connect version to v2, but it wasn't as simple as updating the version from 1 to 2:
```diff
// src/wallet-connect.ts
-connectors: w3mConnectors({ version: 1, chains, projectId }),
+connectors: w3mConnectors({ version: 2, chains, projectId }),
```
It turns out, when using the v2 connector and you construct a smart contract with a `signer`, it fails when calling a method on the smart contract that loads data from the chain. **Note** this is when using a wallet (like Trust/Rainbow) via Wallet Connect, MetaMask works fine. To fix the data loading issue, it boils down to using the `provider` instead:
```diff
-ConvenienceFactory.connect(contracts.convenience, signer);
+ConvenienceFactory.connect(contracts.convenience, provider);
```
And connecting as the `signer` when …
=> Use v2 wallet connector (Wallet Connect)

config-overrides.js, package.json, setup-jest.js, src/__test_utils__/index.tsx, src/__test_utils__/mock-wagmi-client.ts, src/app.tsx, src/chain-data/adapters.ts, src/chain-data/context.tsx, src/components/notifications/notifications.tsx, src/components/notifications/storage-full-notification.module.scss, src/components/notifications/storage-full-notification.tsx, src/index.scss, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/wallet-connect.ts, yarn.lock
Fixes #425 
According to [this issue](https://github.com/WalletConnect/web3modal/issues/1345), the problem should be resolved by updating to the latest `wagmi`.
- upgrades `wagmi` to v1, which comes with `viem`
- upgrades Typescript to v5 (`viem` depends on Typescript v5)
- shows a warning message when `localStorage.setItem()` fails
- adapters provided by `wagmi` (https://wagmi.sh/react/ethers-adapters) were used to convert the `viem` public and wallet clients to the `ethers` provider and signer.
- I don't have full confidence that the original issue is resolved, so I thought it would be a good idea to let the user know if/when it happens again and to give them the ability to quickly sort it out.
=> Upgrade wagmi to v1

package.json, src/pages/proposal-commons/proposal-details/proposal-details.tsx, yarn.lock
Follow up to https://github.com/api3dao/api3-dao-dashboard/pull/424
- updates the browserlist to filter out ancient browsers (IE and Android browser version <= 4.4.4) so that transpilation doesn't interfere with BigInts. The issue is described [here](https://github.com/hirosystems/stacks.js/issues/1096#issuecomment-946350299)
=> Upgrade wagmi to v1 (part 2)

.github/workflows/build-docker.yml
"Attestations are supported with version 4 and later of the docker/build-push-action" ([source](https://docs.docker.com/build/ci/github-actions/attestations/)) - this PR updates from v3 to v5, and updates other steps as well.
EDIT: The `production` branch is the only one from which images get pushed because of this bool:
https://github.com/api3dao/api3-dao-dashboard/blob/b8befd30d13bf352c12b2bfd4e0a0b239352c5de/.github/workflows/build-docker.yml#L37
so I originally opened the PR against `production`, but realized that didn't make sense since commits are merged from `main` to `production`. In rebasing, I did notice GitHub is having some trouble reconciling `main` and `production`: see [this compare](https://github.com/api3dao/api3-dao-dashboard/compare/production...main). I'm guessing, …
=> Bump versions of Actions steps in order to add provenance

.github/workflows/build-docker.yml, Dockerfile, README.md
Closes #439 
- builds the Docker image with the `REACT_APP_MAINNET_PROVIDER_URL` env variable through the use of a build arg
- updates documentation
=> Provide REACT_APP_MAINNET_PROVIDER_URL env variable when building Docker image

README.md
When attempting to verify the fleek build locally using the following command:
https://github.com/api3dao/api3-dao-dashboard/blob/ef58bfb106d4419c5fbc9828ec4a335831dce883/README.md?plain=1#L78 
with the suggested `docker-compose.yml` file:
https://github.com/api3dao/api3-dao-dashboard/blob/ef58bfb106d4419c5fbc9828ec4a335831dce883/README.md?plain=1#L56-L76
I received the following package incompatibility build error originating from the use of the `fleek/create-react-app` image (which is 3 years old and uses Node.js 16) 
```
❯ docker-compose run --rm app
WARN[0000] /home/derek/api3/api3-dao-dashboard/docker-compose.yml: `version` is obsolete
[+] Creating 1/0
✔ Network api3-dao-dashboard_default  Created                                                                                  0.0s …
```
=> Bump fleek/create-react-app to node-18 for local verification

cypress/e2e/new-proposal.cy.ts, src/logic/proposals/encoding/encoding.test.ts, src/logic/proposals/encoding/encoding.ts
- extends the proposal validation logic to return a new validation error message when the target contract signature includes whitespace
- rearranges the validation logic to produce validation messages in the following order (to better align with the field order that the user sees on the screen):
1. target address
2. target contract signature
3. parameters
=> Extend proposal validation to catch whitespace in target contract signature

.github/workflows/main.yml, package.json, yarn.lock
This is a substitute for several open dependency PRs. ~Note also the bump from Node.js 16 to 18, which was chosen, rather than 20, because the latest `fleek/create-react-app` image described in the "Verifying the Fleek build" README section [is Node 18](https://hub.docker.com/r/fleek/create-react-app/tags).~
EDIT: Bumping to Node 18 causes Cypress failures, so I think this should be tackled separately
=> Bump packages and update Actions workflow

cypress/e2e/footer.cy.ts, cypress/support/common.ts, src/components/checkbox/checkbox.module.scss, src/components/checkbox/checkbox.tsx, src/components/checkbox/index.ts, src/components/external-link/external-link.tsx, src/components/icons/check.tsx, src/components/icons/index.ts, src/components/layout/error-reporting-notice/error-reporting-notice.module.scss, src/components/layout/error-reporting-notice/error-reporting-notice.tsx, src/components/layout/layout.tsx, src/components/layout/privacy-settings-modal/index.ts, src/components/layout/privacy-settings-modal/privacy-settings-modal.module.scss, src/components/layout/privacy-settings-modal/privacy-settings-modal.tsx, src/components/notifications/storage-full-notification.tsx, src/index.tsx, src/utils/analytics.ts, src/utils/error-reporting.ts, src/utils/generic.test.ts, src/utils/generic.ts, src/utils/links.ts
Closes #467 
- adapts existing consent banner
- implements consent logic from Market
- adds Privacy Settings modal
- adds Checkbox component
| Banner |
|--------|
| <img width="804" alt="image" src="https://github.com/user-attachments/assets/40be5650-fcb3-40c0-9f11-6081203968dc"> | 
| Modal |
|--------|
| <img width="804" alt="image" src="https://github.com/user-attachments/assets/570c2fb0-2b8c-41ec-a74d-3e0800f62989"> |
=> Add cookie consent logic

src/pages/proposal-commons/proposal-list/proposal-list.module.scss
Following the [comment](https://github.com/api3dao/api3-dao-dashboard/pull/499#discussion_r1858058834) and the clarification from designers:
=> Display proposal title in two lines on non-desktop screens

src/components/modal/modal.module.scss, src/components/modal/modal.tsx, src/pages/proposals/forms/new-proposal-form.module.scss, src/pages/proposals/forms/new-proposal-form.tsx
First point from the #506 
- see title
- [Designs](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108151&node-type=frame&m=dev)
- [Discussion](https://api3workspace.slack.com/archives/C06SH3YFMK7/p1732700734669899)
=> Change Help tooltip to external link in the New Proposal modal

cypress/e2e/keyboard-navigation.cy.ts, src/components/navigation/navigation.module.scss, src/components/navigation/navigation.tsx, src/components/sign-in/sign-in.module.scss, src/components/sign-in/sign-in.tsx
Part of #506 
- Moves the connect button to the top bar on screens with width under 1200px and shorten the label from "Connect Wallet" to just "Connect"
| Before | After |
|---------|------|
|![image](https://github.com/user-attachments/assets/4ed7abba-8e05-49b4-879b-142127623145)| ![image](https://github.com/user-attachments/assets/13d0f5ef-6189-4461-8570-20a32572c4d2)
=> Move connect button to the navigation bar on small screens

cypress/e2e/keyboard-navigation.cy.ts, src/components/layout/layout.module.scss, src/components/layout/layout.tsx, src/styles/fonts.module.scss, src/utils/links.ts
Closes #521 
- Changes "About API3" label to just "Api3.org"
- Adds second row to the footer with copyright and links to privacy pages
=> Add privacy links & copyright to the footer
