api3dao/api3-dao-dashboard

cypress/integration/new-proposal.spec.ts, cypress/integration/staking.spec.ts, cypress/support/commands.ts, cypress/support/index.d.ts, hardhat/scripts/create-proposals.ts, src/components/input/input.tsx, src/logic/proposals/encoding.test.ts, src/logic/proposals/encoding.ts, src/pages/proposal-commons/proposal-list/proposal-list.tsx, src/pages/proposals/forms/new-proposal-form.module.scss, src/pages/proposals/forms/new-proposal-form.tsx, src/pages/proposals/proposals.tsx, src/utils/generic.ts
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/134
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/181
and couple of errors reported on Discord and internal testing.
=> New proposal form validation

src/logic/dashboard/hooks.ts, src/pages/proposals/forms/delegate/delegate-form.tsx, src/utils/messages.ts
Based on google doc from Tamara: https://docs.google.com/document/d/1BCeij033tugYdKT0FHJwElo1cS7out6tS93ynnnyafE/edit
And I made some small touches to it. Mainly some missing punctuation, sometimes changed a word or updated messages not covered in the doc (because they were added in the meantime).
=> Improve and make error messages consistent

src/chain-data/helpers.ts, src/components/sign-in/sign-in.tsx, src/logic/dashboard/hooks.ts, src/logic/proposals/hooks/active-proposals.ts, src/logic/proposals/hooks/get-proposals.ts, src/logic/proposals/hooks/history-proposals.ts, src/logic/proposals/hooks/load-by-ids.ts, src/logic/treasury-and-delegation/use-treasury-and-delegation.ts, src/logic/vesting/hooks.ts, src/pages/dashboard/dashboard.tsx, src/pages/dashboard/forms/confirm-unstake-form.tsx, src/pages/dashboard/forms/token-amount-form.tsx, src/pages/dashboard/forms/token-deposit-form.tsx, src/pages/dashboard/pending-unstake-panel/pending-unstake-panel.tsx, src/pages/dashboard/unstake-banner/unstake-banner.tsx, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposal-commons/proposal-list/proposal-status/proposal-status.tsx, src/pages/proposals/delegation/delegation.tsx, src/pages/proposals/forms/delegate/delegate-form.tsx, src/pages/proposals/proposals.tsx, src/pages/vesting/vesting.tsx, src/utils/error-handling.ts, src/utils/index.ts
Implements discussion point 3) in https://api3workspace.slack.com/archives/C020RCCC3EJ/p1625224629006600
Also: 
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/84
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/41
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/28
**Review commit by commit.** 
One of the commits just changes adds the return statement on a single line to make the code a bit shorter and (subjectively) more readable. This however changes the semantics of the code a bit (return nothing vs return something). In case you disagree with that change, I'll drop that commit.
=> Handle all errors, simplify error handling code

src/pages/proposal-commons/treasury/treasury.module.scss, src/pages/proposal-commons/treasury/treasury.tsx
Resolves https://api3workspace.slack.com/archives/C020RCCC3EJ/p1624369090018600
=> Add treasury tooltip

src/chain-data/state.ts, src/logic/proposals/hooks/get-proposals.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx
https://api3workspace.slack.com/archives/C020RCCC3EJ/p1625224629006600
=> Implement discussion link

cypress/integration/delegation.spec.ts, cypress/integration/keyboard-navigation.spec.ts, cypress/integration/staking.spec.ts, src/chain-data/helpers.ts, src/chain-data/state.ts, src/components/dropdown/dropdown.module.scss, src/components/sign-in/sign-in.tsx, src/components/textarea/textarea.module.scss, src/logic/proposals/hooks/active-proposals.ts, src/logic/proposals/hooks/get-proposals.ts, src/logic/proposals/hooks/history-proposals.ts, src/logic/proposals/hooks/load-by-ids.ts, src/logic/treasury-and-delegation/use-treasury-and-delegation.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposals/delegation/delegation.tsx, src/pages/proposals/forms/delegate/delegate-form.tsx, src/utils/messages.ts
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/203
I think I am looking up the ENS records for all places necessary, but have thought about what I might have missed.
=> Resolve ENS names and addresses, fix e2e tests

.eslintrc.json, cypress/.eslintrc.json, dev-scripts/.eslintrc.json, hardhat/.eslintrc.json, package.json, src/chain-data/context.tsx, src/components/notifications/notifications.tsx, src/logic/proposals/hooks/active-proposals.ts
This has sometimes come up in reviews and I've wrote it in my TODO list for later.
Later is now I guess.
=> Add "no console" and "prefer const" rule

src/pages/proposal-commons/proposal-details/vote-form/vote-form.tsx
There was one more bug similar to https://github.com/api3dao/api3-dao-dashboard/commit/ec3207f73851e7cb828308b72e7e516942ab9104 
There are no more (I checked).
=> Fix vote radio button

README.md
See title. Added both of you because it's probably relevant.
=> Add instructions about updating name servers

src/chain-data/state.ts, src/logic/proposals/hooks/get-proposals.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/226
=> Remove discussion URL

cypress/integration/new-proposal.spec.ts, src/components/radio-button/radio-button.tsx, src/pages/history/history.tsx, src/pages/proposal-commons/proposal-details/vote-form/vote-form.tsx, src/pages/proposals/forms/new-proposal-form.tsx
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/217
=> Remove name parameter from radio button

src/contracts/helpers.test.ts, src/contracts/helpers.ts, src/logic/dashboard/selectors.ts, src/pages/dashboard/staking/staking-pool.module.scss, src/pages/dashboard/staking/staking-pool.tsx
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/208
=> Fix correct staking calculation, add clarification tooltips

hardhat/scripts/create-proposals.ts, src/chain-data/state.ts, src/logic/proposals/encoding.test.ts, src/logic/proposals/encoding.ts, src/logic/proposals/hooks/get-proposals.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/pages/proposals/forms/new-proposal-form.tsx, src/pages/proposals/proposals.tsx
Fixes https://api3workspace.slack.com/archives/C02ALA11APM/p1628590492006400 
which was requested https://forum.api3.org/t/ens-name-for-proposal-creator/289
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/224
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/223
=> Ens parameters

src/pages/dashboard/staking/staking-pool.module.scss, src/pages/dashboard/staking/staking-pool.tsx
Sorry about this, I probably introduced this regression when I was fixing the layout for mobile/tablet resolutions...
We actually have a pretty complex layout tbh :/
=> Fix minor staking page visuals

src/pages/proposal-commons/proposal-details/proposal-details.tsx
Fixes https://github.com/api3dao/api3-dao-dashboard/issues/238
More context: https://api3workspace.slack.com/archives/C02ALA11APM/p1629371737050900
=> Fix back button

src/pages/proposal-commons/proposal-details/proposal-details.module.scss, src/pages/proposal-commons/proposal-details/proposal-details.tsx
https://api3workspace.slack.com/archives/C02ALA11APM/p1629097143026700
=> Support http links in proposal details

cypress/integration/keyboard-navigation.spec.ts, cypress/integration/staking.spec.ts, src/logic/dashboard/selectors.ts
Based on https://docs.google.com/document/d/1ESEkemgFOhP5_tXajhuy5Mozdm8EwU1O2YSKSBwnrUQ/edit?disco=AAAAUnRCMzM
=> Fix incorrect unstake and withdraw UI logic

cypress/integration/new-proposal.spec.ts, src/pages/proposals/forms/new-proposal-form.tsx
Fixes #255 
The cypress test has also been updated to assert that the default is Secondary.
=> Change default proposal type to Secondary

cypress/integration/keyboard-navigation.spec.ts, hardhat/hardhat.config.ts, src/app.tsx, src/components/icons/ArrowLeftIcon.tsx, src/components/icons/ArrowRightIcon.tsx, src/components/icons/search-icon.tsx, src/components/input/input.tsx, src/components/menu/menu.tsx, src/index.scss, src/logic/policies/data.ts, src/pages/claim-details/claim-details.tsx, src/pages/new-claim/new-claim.tsx, src/pages/policies/index.tsx, src/pages/policies/pagination.module.scss, src/pages/policies/pagination.test.tsx, src/pages/policies/pagination.tsx, src/pages/policies/policies.module.scss, src/pages/policies/policies.tsx, src/pages/policies/policy-list.module.scss, src/pages/policies/policy-list.tsx, src/utils/messages.ts
- Adds the Policies page with searching, filtering, and pagination
- Updates the New Claim page to capture an USD amount
- URL search params was used to drive the searching, filtering, and pagination
- I decided to write the pagination component myself, as the library options out there are unnecessarily clunky and not very composable
- react-paginate: 22KB min, 5.4KB min+gz
- rc-pagination: 16KB min, 5.2KB min+gz
=> DAO-157 Policy list page

src/pages/proposal-commons/treasury/hooks.ts
=> DAO-147 Format treasury amounts

.github/workflows/main.yml, src/logic/proposals/hooks/load-by-ids.ts, src/pages/proposal-commons/proposal-details/proposal-details.tsx
It fixes the loop that the loading gets stuck in. The loop being:
1. The ID gets decoded into a BigNumber from the URL on render
2. The load gets triggered (as ID is a dependency)
3. The proposal finishes loading
4. Go to step 1
=> DAO-193 Fix proposal repeatedly loading on Proposal Details page

.github/workflows/main.yml, .gitignore, cypress.json, cypress/integration/malicious-proposal-validation.spec.ts, cypress/integration/staking.spec.ts, hardhat/hardhat.config.ts, package.json, src/logic/proposals/encoding/encoding.test.ts, src/logic/proposals/encoding/encoding.ts, src/pages/proposal-commons/proposal-details/proposal-details.module.scss, src/pages/proposal-commons/proposal-details/proposal-details.tsx
- shows a warning on the Proposal Details page when a mismatch between the original EVM script and the re-encoded EVM script has been detected.
- adds a hardhat task for creating a proposal
=> DAO-194 Show a warning when there is a mismatch between the original EVM script and the re-encoded EVM script

src/components/usd-input/index.ts, src/components/usd-input/usd-input.module.scss, src/components/usd-input/usd-input.tsx, src/index.scss, src/pages/new-claim/confirmation.tsx, src/pages/new-claim/new-claim-form.module.scss, src/pages/new-claim/new-claim-form.tsx, src/pages/new-claim/new-claim.tsx
- updates the New Claim form to enter the USD amount with 2 decimal places
- minor copy updates to align with latest design
A `UsdInput` component was added to better encapsulate the usage of the `NumberFormat` component.
https://user-images.githubusercontent.com/747979/189898675-d3db2565-8c50-4085-b344-c64415723fac.mov
=> DAO-177 Enter claim USD amount with 2 decimal places

src/components/back-button/back-button.module.scss, src/pages/components/proposal-details/proposal-details.module.scss, src/pages/components/proposal-details/proposal-details.tsx, src/utils/image-list.ts
- it uses the BackButton component on the Proposal Details page
- changes the "Back to X" text to just "Back" for consistency with the Policy & Claim pages
=> DAO-204 Use the BackButton component on the Proposal Details page

src/components/bordered-box/bordered-box.tsx, src/pages/components/policies/policy-list.module.scss, src/pages/components/policies/policy-list.tsx, src/pages/components/search-form/search-form.module.scss, src/pages/policy-details/policy-details.module.scss, src/pages/policy-select/policy-select.module.scss, src/pages/policy-select/policy-select.tsx
- updates the responsive styling of the PolicyList component
- adds skeleton for pending remaining coverage
- updates the header of the PolicySelect page
- other minor tweaks
https://user-images.githubusercontent.com/747979/195362575-462ebf22-d8a9-4ece-9a83-a8f78f12dbe7.mov
=> DAO-222 Policy pages styling updates

Dockerfile, README.md
=> Pin production branch Docker parent image to node:16-alpine

.github/workflows/build-docker.yml
Same as #359 (including image name & tag feedback updates) but for the `production` branch
=> [production] Add docker build and push CI workflow

.github/workflows/build-docker.yml
Follow-on from https://github.com/api3dao/api3-dao-dashboard/pull/360#issuecomment-1325386654
=> Specify Docker image using api3 base

cypress/e2e/policy-updates.cy.ts
- adds a test for policy downgrades and upgrades
- adds a test for metadata updates
=> DAO-232 Cypress tests: Policy updates (upgrades, downgrades, metadata updates)

src/components/layout/layout.tsx
Issue: https://github.com/api3dao/data-feeds/issues/1505
Updating docs link after changes in the docs
=> Update docs link

src/components/dropdown/dropdown.module.scss, src/components/dropdown/dropdown.tsx, src/components/sign-in/sign-in.module.scss, src/components/sign-in/sign-in.tsx
The designs for the account dropdown were slightly adjusted, mainly the background but also some spacings and sizes.
Designs: [Figma](https://www.figma.com/design/NG6QClnVrvPRZ5gJ3s0zen/%E2%9F%81--Api3-DAO---Branding-Update?node-id=8676-108481&node-type=instance&m=dev)
| Before | After |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/e685366d-0bab-488c-95bc-e9e840cde812) | ![image](https://github.com/user-attachments/assets/a08396eb-7ac7-42a0-8aba-fe4e97ab25f8) |
=> Update account dropdown 

public/wallet-disconnected.svg, src/pages/proposal-commons/proposal-details/disconnected-proposal-page.module.scss, src/pages/proposal-commons/proposal-details/disconnected-proposal-page.tsx, src/pages/proposal-commons/proposal-details/proposal-details.tsx, src/utils/image-list.ts
Part of #506 
- The UI of the proposal page with a disconnected wallet
| Before | Now |
|--------|-------|
| ![image](https://github.com/user-attachments/assets/89bc4406-525c-44cd-8ba4-2a9e27d97290) | ![image](https://github.com/user-attachments/assets/bf0ce433-e4ad-41ff-8cc4-9dce7cb72ce4) |
=> Add UI for disconnected state of the proposal page

src/pages/not-found/not-found.module.scss, src/pages/not-found/not-found.tsx
Part of #506 
- just a small fix changing the breakpoint from `sm` to `md`
=> Fix breakpoints on 404 page

.env.example, Dockerfile, README.md, cypress/e2e/malicious-proposal-validation.cy.ts, public/index.html, src/app.tsx, src/components/external-link/external-link.test.tsx, src/components/layout/layout.tsx, src/logic/proposals/encoding/encoding.test.ts, src/logic/proposals/encoding/index.ts, src/wallet-connect.ts
I suppose this doesn't warrant another release
=> Replace API3 -> Api3 (except when the token is being referred)
